name: integration-test

on:
    push:
      branches:
        - "master"
    workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
        
      - name: Build & Install Playwright
        run: dotnet build
    
      - name: Ensure browsers are installed
        run: pwsh tests/Customers.WebApp.Tests.Integration/bin/Debug/net6.0/playwright.ps1 install --with-deps
    
      - name: Run your tests
        run: |
          ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
          dotnet tests
